# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# logger:
#   default: notset

# Text to speech
tts:
  - platform: google_translate

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config

recorder:
  db_url: !secret db_url

lovelace:
  mode: yaml
  resources:
    - url: /local/community/monster-card/monster-card.js
      type: js
    - url: /local/community/multiple-entity-row/multiple-entity-row.js?v=2.2.0
      type: module
    - url: /local/community/lovelace-layout-card/layout-card.js
      type: module
    - url: /local/community/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js?v=3.0.1
      type: module
    - url: /local/community/popup-backdrop-filter/popup-backdrop-filter.js
      type: module
    - url: /local/community/bar-card/bar-card.js
      type: module
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/community/seventeen-track-card/seventeen-track-card.js
      type: module
    - url: /local/community/lovelace-paper-buttons-row/paper-buttons-row.js
      type: module

mobile_app:

browser_mod:

frontend:
  themes: !include_dir_merge_named themes

tado:
  username: !secret tado_username
  password: !secret tado_password

xiaomi_aqara:
  discovery_retry: 5
  gateways: !secret xiaomi_aqara_gateways

http:
  base_url: !secret base_url

notify:
  - platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: telegram
    name: telegram_notifier
    chat_id: !secret telegram_chat_id_kirill

device_tracker:
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

switch:
  - platform: xiaomi_miio
    name: Floor lamp
    host: !secret xiaomi_switch_1_ip
    token: !secret xiaomi_switch_1_token
  - platform: xiaomi_miio
    name: Christmas tree
    host: !secret xiaomi_switch_2_ip
    token: !secret xiaomi_switch_2_token
  - platform: xiaomi_miio
    name: Power strip
    host: !secret xiaomi_power_strip_ip
    token: !secret xiaomi_power_strip_token

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

media_player:
  - platform: androidtv
    name: MiBox 3
    host: !secret xiaomi_mibox3_ip
    adb_server_ip: !secret hass_ip
    adb_server_port: !secret adb_server_port

octoprint:
  host: !secret octopi_ip
  api_key: !secret octopi_api_key
  name: Anycubic i3 Mega
  bed: true
  number_of_tools: 1

shell_command:
  # Setup on macos
  # System Preferences > Sharing > Remote Login
  # ssh root@hassio.local
  # ssh-keygen
  # /config/.ssh/id_rsa
  # ssh-copy-id -i /config/.ssh/id_rsa USER@XXX.XXX.X.X
  restart_hass_docker: !secret restart_hass_docker

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    trusted_networks:
      - 149.154.160.0/20
      - 91.108.4.0/22
    allowed_chat_ids:
      - !secret telegram_chat_id_kirill
